### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by darrillaga** [bechte/junit-hierarchicalcontextrunner#16]
Hi, 

It would be great if I would apply this structure to the Android instrumentation tests.

Thanks,

**Comment by bechte** [comment]
Any updates here? What is missing? Otherwise, I will close the issue.

**Comment by syslogic** [comment]
Android Architecture Components [Navigation](https://developer.android.com/topic/libraries/architecture/navigation/navigation-implementing) would meanwhile provide some kind of hierarchy one could follow (probably that would be better than just prsing the `Manifest.xml` for Activity entry-points), while there also is a test-runner:

    dependencies {

        def nav_version = "1.0.0-alpha05"

        implementation "android.arch.navigation:navigation-fragment:$nav_version" // use -ktx for Kotlin
        implementation "android.arch.navigation:navigation-ui:$nav_version" // use -ktx for Kotlin

        // optional - Test helpers
        androidTestImplementation "android.arch.navigation:navigation-testing:$nav_version" // use -ktx for Kotlin
    }
