### ISSUE TITLE
Integrate 'HierachicalContextRunner' via a PR in the official JUnit repository

### ISSUE THREAD

**Issue by qabbasi** [bechte/junit-hierarchicalcontextrunner#18]
I think this will boost up the popularity of this awesome and very useful (custom) JUnit runner.

**Comment by qabbasi** [comment]
Any chance for an integration with the JUnit repo? Keen to see it :smiley_cat:

**Comment by bechte** [comment]
Hi. Thanks for liking the runner. :-)

What exactly would you like to see / what do you expect? I don't get the idea. :-(

Are you talking about a code dependency or rather a official promotion?

The runner is listed in the official documentation at junit.org, see:
https://github.com/junit-team/junit/wiki/Custom-runners

**Comment by qabbasi** [comment]
de.bechte.junit -> With integration I meant to have your runner located in the official org.junit pkg :smile:
I often see that developers want to have mvn dependencies from the 'officials' rather then from not well-known sources (according to them). It was just an idea. (hopefully a hanging fruit :green_apple: task)

**Comment by bechte** [comment]
Oh yeah, from a code side perspective that would be easy to do. I will have an discussion with the JUnit developer team. Thanks for pushing that way.

**Comment by bechte** [comment]
Update: The hierarchical context runner will be part of the JUnit5 release. We already integrated the feature, therefore, there will be no integration into JUnit4.
