### ISSUE TITLE
Inner classes marked @Ignore are not skipped

### ISSUE THREAD

**Issue by mchenryc** [bechte/junit-hierarchicalcontextrunner#20]
The `@Ignore` annotation works on the outer class (skipping all tests cases) and on methods (skipping individual test cases), but if an inner class is marked @Annotated, its test cases are not skipped.

Given:

    @RunWith(HierarchicalContextRunner.class)
    public class AppTest {
      public class RunContext {
        @Test
        public void shouldRun() throws Exception {
          assertTrue(true);
        }
      }
      @Ignore
      public class IgnoreClassContext{
        @Test
        public void shouldIgnore() throws Exception {
          assertTrue(false);
        }
      }
      public class IgnoreMethodContext{
        @Ignore
        @Test
        public void willIgnore() throws Exception {
          assertTrue(false);
        }
      }
    }

I expect the result:

    Tests run: 3, Failures: 0, Errors: 0, Skipped: 2

But instead, `shouldIgnore()` test fails, with the result:

    Tests run: 3, Failures: 1, Errors: 0, Skipped: 1

**Comment by bechte** [comment]
I will have a lock at this issue tonight and probably release a new version after fixing, as I would also like to update the dependency to junit-4.12-beta-1 to junit-4.12.

**Comment by bechte** [comment]
Unfortunately, I cannot fire ignore notifications for all tests within the context, but I can simply ignore the context at all. Therefore, given the example above, the result would be:

```
Tests run: 2, Failures: 0, Errors: 0, Skipped: 1
```

**Comment by bechte** [comment]
Solved with given limitation.
