### ISSUE TITLE
Create new release from master

### ISSUE THREAD

**Issue by mouyang** [bechte/junit-hierarchicalcontextrunner#32]
I use this library and need the fix for issue #28.  It would be nice to have this fix in an official release of the master branch available in Maven Central.  It would be great if you have the availability to do that.  I am aware of the Release-HowTo wiki and I would do it myself but I'm afraid of making a mistake and damaging working released artifacts (it sounds like version 4.12.2, tag r4.12.2, new deployment version 4.12.3-SNAPSHOT is sufficient).  If you can assure me the steps in the wiki are foolproof then I can create a new release for you.  This is by no means an urgent request, I am able to continue on with what I need to do by building the project locally.

**Comment by mouyang** [comment]
@bechte I tried to release a new version as per the Release-HowTo wiki but I stopped when I was asked for a GPG Passphrase.  If it is not possible for me to release a new version, can you or someone else do it?

**Comment by bechte** [comment]
Hi. Sorry for being late. I was on vacation for a couple of weeks and didn't spend a thought on programming as my second child was born. 😄 

Now being back to work and after catching up things that need to be done, I'd love to release another version. I will do this right away tomorrow.

**Comment by mouyang** [comment]
Cheers on the vacation and the new child.  I just came back from vacation myself.

**Comment by mouyang** [comment]
Hello, have you had an opportunity to do make a new release?  If not, I understand.  I have not done better with looking into automating the release.

**Comment by bechte** [comment]
Thanks for you effort. I will try to automate the release as you have proposed.

**Comment by bechte** [comment]
Release 4.12.2 has just been released and uploaded to https://oss.sonatype.org. Process may take a couple of hours to complete.

**Comment by mouyang** [comment]
I checked this morning but I don't see it in sonatype or maven central.  Can you look into this?

**Comment by bechte** [comment]
Probably a timing issue? I republished it, just to make sure it is released.

Download is possible for me via: https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=de.bechte.junit&a=junit-hierarchicalcontextrunner&v=4.12.2&e=jar

Please verify again. Thanks.

**Comment by mouyang** [comment]
I just verified it on oss.sonatype.org, and it just showed up on Maven Central.  Thank you so much for looking into this.  I appreciate your help on it.
