### ISSUE TITLE
Automate Releases

### ISSUE THREAD

**Issue by mouyang** [bechte/junit-hierarchicalcontextrunner#33]
A fix for #28 was merged into master 2 years ago, but it has not been incorporated into an official release.  As a result, a fix for an issue in another project mockito/mockito#1578 is dependent on a dev snapshot of this library (I'm certain they will reject my fix for this very reason).  As a developer that needs this fix, I can work around this by building master myself and releasing to my own Maven repository.  It would be preferable however if releases were made automatically through some tool like Travis CI, especially since busy lives get in the way of doing this manually.

**Comment by bechte** [comment]
Great idea, would you like to create a PR for that? Otherwise I will add it as soon as I can.

**Comment by mouyang** [comment]
I would love to give it a try when I get an opening to do so.

**Comment by mouyang** [comment]
Initial attempt made in a pull request with some open questions.  If you want, you can assign this ticket to me.

**Comment by mouyang** [comment]
There is a passphrase error I'm seeing when I try to run the build.  Please advise on how to get past following error https://travis-ci.org/mouyang/junit-hierarchicalcontextrunner/builds/488674153#L1974

**Comment by bechte** [comment]
Solved automation of releases. A release will be automatically triggered whenever a merge into master occurs.
