### ISSUE TITLE
Support for static inner classes

### ISSUE THREAD

**Issue by bechte** [bechte/junit-hierarchicalcontextrunner#4]
People have asked me, why the HierarchicalContextRunner does not support tests within static inner classes. This issue was created to start a discussion on this topic.

I was thinking about running tests for inner static classes as well, but I didn't see the point for doing so. They somehow break the hierarchical behavior, as they haven't direct access to the member variables (and even methods like the @Before/@After) of the enclosing class(es). Therefore, they are IMHO not much useful within the context hierarchy. I would rather have a new test class instead of an inner static class. 

A typical use-cases I see for static inner class are stubs providing test-data for the tests or helpers. But I wouldn't like to have test in theses classes, would I?

Using the HierarchicalContextRunner it is unnecessary (and not wanted) to extend classes used to create a context, i.e. the inner member classes. Use inner member class definitions (public class X) as if they where context declarations (context X). Do not extend them.

I am looking forward to discussing with you. :)

**Comment by ekoutanov** [comment]
Six years late to the party, but that aside, the only minor snag with not supporting static classes is that modern IDEs (e.g. IntelliJ) bring up minor warnings when a nested class can be made static when they don't access the encompassing instance variables. This is actually how I discovered that this behaviour wasn't supported (by simply following the IDEs suggestions).

**Comment by bechte** [comment]
> Six years late to the party, but that aside, the only minor snag with not supporting static classes is that modern IDEs (e.g. IntelliJ) bring up minor warnings when a nested class can be made static when they don't access the encompassing instance variables. This is actually how I discovered that this behaviour wasn't supported (by simply following the IDEs suggestions).

True 🥇  ... but this is **more** due to a _lack of support_ of hierarchical tests. While the inner classes do not access the methods directly (which could be statically detected by IntelliJ), they are accessed during test execution by the HierarchicalContextRunner. Therefore, I would change that warning within IntelliJ, but I think we adapted the behavior with JUnit5 and support it, so it might not be necessary to raise this flag anymore. What do you think?

**Comment by ekoutanov** [comment]
Philosophically, you are right of course. But then, to that point, if IntelliJ/Eclipse supported hierarchical test layouts natively, we wouldn't have a need for this awesome library...

Unfortunately some projects aren't in the position to adopt JUnit 5.x anytime soon. Problem is that suppressing these types of warnings in an IDE also conceals potentially genuine issues in the rest of the code base. For those on 4.x, having a solid solution to this (admittedly minor issue) would be great. I feel that, if this were supported, it wouldn't 'dilute' the intention behind `hierarchicalcontextrunner` in any way, and it certainly won't break any backward compatibility. I think @paschelino 'kitchen knife' metaphor is very fitting here.
